name: CD for React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS CLI
    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set region $AWS_REGION

    # Step 3: Update ECS Service
    - name: Update ECS Service
      env:
        AWS_REGION: us-east-1
        CLUSTER_NAME: my-ecs-cluster
        SERVICE_NAME: my-react-app-service
      run: |
        # Get the latest image URI
        IMAGE_URI=$(aws ecr describe-images --repository-name my-react-app --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageUri' --output text)
        
        # Update ECS service
        aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
