name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - main  # or the branch you want to trigger the pipeline on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up AWS CLI and Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log into Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: eu-north-1  # Replace with your region

    # Debugging step to ensure secrets are correctly set
    - name: Debug Secrets
      run: |
        echo "ECR Registry: ${{ secrets.ECR_REGISTRY }}"
        echo "ECR Repository: ${{ secrets.ECR_REPOSITORY }}"
        echo "Image Tag: ${{ secrets.IMAGE_TAG }}"
        echo "AWS Region: eu-north-1"
    
    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG }} .
    
    # Debugging step to check if the build was successful
    - name: Debug Docker Image
      run: |
        docker images

    # Push the Docker image to Amazon ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG }}

    # Debugging step to check if push was successful
    - name: Debug Docker Push
      run: |
        echo "Docker push complete for ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG }}"

