name: Build and Push Docker Image to ECR and Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: eu-north-1

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-react-app .

      # Step 5: Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag my-react-app:latest 816069125679.dkr.ecr.eu-north-1.amazonaws.com/my-react-app:latest

      # Step 6: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push 816069125679.dkr.ecr.eu-north-1.amazonaws.com/my-react-app:latest

      # Step 7: Update ECS service to deploy new image
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster my-ecs-cluster-three \
            --service my-ecs-service \
            --force-new-deployment \
            --region eu-north-1
