name: Build and Push Docker Image to Amazon ECR

on:
  push:
    branches:
      - main  # or the branch you want to trigger the pipeline on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1  # Set region here

    # Log into Amazon ECR using the AWS CLI
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG }} .

    # Debug Docker Image
    - name: Debug Docker Image
      run: |
        docker images

    # Push the Docker image to Amazon ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG }}

    # Debug Docker Push
    - name: Debug Docker Push
      run: |
        echo "Docker push complete for ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ secrets.IMAGE_TAG }}"

