name: CI for React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to AWS ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker image
      env:
        AWS_REGION: us-east-1
      run: |
        # Define variables
        IMAGE_NAME=my-react-app
        ECR_REGISTRY=$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.us-east-1.amazonaws.com
        
        # Build Docker image
        docker build -t $IMAGE_NAME .
        
        # Tag Docker image
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
        
        # Push to ECR
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest
